name: DevSecOps Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build Docker image
      run: docker build -t devsecops-demo .

    - name: Run container test
  run: |
    docker run -d -p 5001:5001 --name app devsecops-demo
    sleep 10
    docker logs app
    curl -v http://localhost:5001
